### ISSUE TITLE
Generic Joystick Component Drift

### ISSUE THREAD

**Issue by tjfentie** [makersmakingchange/Spruce-Mini-Joystick#4]
In the BOM there are two versions of the joystick module to buy, the adafruit and the generic one. The generic one [Link](https://www.amazon.ca/dp/B07VXPFB9Q?ref=cm_sw_r_cso_cp_apin_dp_JCV5F8YBPY93H0SNAY4T_2&ref_=cm_sw_r_cso_cp_apin_dp_JCV5F8YBPY93H0SNAY4T_2&social_share=cm_sw_r_cso_cp_apin_dp_JCV5F8YBPY93H0SNAY4T_2&starsLeft=1&skipTwisterOG=1) seems to have some inconsistency when it comes to quality of orders resulting in drift in the final built device.

We need to determine if we pull the generic one from the BOM/instructions and just suggest Adafruit module to avoid broken units.

**Comment by jversloot** [comment]
Drift is only present when used with the Xbox Adaptive Controller (XAC) and is due to the built-in autocalibration. This issue has been resolved by providing instructions on the order to plug in the joystick cable and switch cable when using with the XAC. Instructions are in the User Guide, and on the website posting, and a brief warning is on the README.
